services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENWEATHERMAP_API_KEY: "SECRET_KEY"
    container_name: main-app
    ports:
      - "8000:8000"
    command: "python src/manage.py runserver 0.0.0.0:8000"